import { Link } from "react-router-dom";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { RESULTS, SEC3_Q8_RESULTS, SEC3_Q9_RESULTS, tier } from "@/data/predictions";
import { THEORY_BANK, THEORY_FLASHCARDS } from "@/data/theory";
import { CLASSIFY_ITEMS, LAYOUT_FORMATS } from "@/data/studyContent";
import { useMemo } from "react";

function useDashboardStats() {
  return useMemo(() => {
    try {
      // Theory scores
      const scoresRaw = localStorage.getItem("lc-theory-scores");
      const scores: Record<string, string> = scoresRaw ? JSON.parse(scoresRaw) : {};
      const attempted = Object.keys(scores).length;
      const gotCount = Object.values(scores).filter(s => s === "got").length;

      // Flashcards known
      const knownRaw = localStorage.getItem("lc-flash-known");
      const known: string[] = knownRaw ? JSON.parse(knownRaw) : [];

      // Classify best
      const classifyBest = Number(localStorage.getItem("lc-classify-best")) || 0;

      // Practice tracker
      const trackerRaw = localStorage.getItem("lc-practice-tracker");
      const tracker: Record<string, boolean> = trackerRaw ? JSON.parse(trackerRaw) : {};
      const practiceCount = Object.values(tracker).filter(Boolean).length;

      // Learn progress
      const learnRaw = localStorage.getItem("lc-learn-progress");
      const learnProgress: Record<string, boolean> = learnRaw ? JSON.parse(learnRaw) : {};
      const modulesComplete = Object.values(learnProgress).filter(Boolean).length;

      return {
        questions: `${attempted}/${THEORY_BANK.length}`,
        practice: attempted > 0 ? `${Math.round((gotCount / attempted) * 100)}%` : "0%",
        flashcards: `${known.length}/${THEORY_FLASHCARDS.length}`,
        classify: `${classifyBest}%`,
        tracker: `${practiceCount}`,
      };
    } catch {
      return { questions: "0", practice: "0%", flashcards: "0", classify: "0%", tracker: "0" };
    }
  }, []);
}

const TOOLS = [
  { href: "/theory", name: "Theory Revision", desc: "Past exam theory questions with marking scheme answers. Practice mode, flashcards, frequency analysis.", stat: `${THEORY_BANK.length}+ questions`, color: "bg-sage-bg border-sage" },
  { href: "/study-tools", name: "Study Tools", desc: "Exam timing calculator, study planner, practice tracker, checklists.", stat: "3 interactive tools", color: "bg-blue-bg border-blue" },
  { href: "/q1-guide", name: "Q1 Adjustment Guide", desc: "Complete reference for every Q1 adjustment type. Filterable by account type.", stat: "Filterable by type", color: "bg-rose-bg border-rose" },
  { href: "/ratios", name: "Q5 Ratios Hub", desc: "Practice papers, formula quiz, Part (b) report guide, sector notes.", stat: "5 papers, 19 formulas", color: "bg-lavender-bg border-lavender" },
];

const Q1_PAIRS = [
  { pair: "Sole Trader + Manufacturing", prob: 48, reason: "Company streak breaks. Non-CO slot alternation pattern points to MFG next." },
  { pair: "Company + Manufacturing", prob: 35, reason: "Company streak holds. Manufacturing appears in either scenario." },
  { pair: "Company + Sole Trader", prob: 15, reason: "Requires MFG skip despite perfect alternation pattern." },
];

export default function Index() {
  const stats = useDashboardStats();
  const shown = RESULTS.filter(r => !r.wildcard).slice(0, 5);
  const q8top = SEC3_Q8_RESULTS.slice(0, 3);
  const q9top = SEC3_Q9_RESULTS.slice(0, 3);

  return (
    <div className="max-w-[900px] mx-auto px-4 sm:px-7 py-8 pb-16">
      {/* Hero */}
      <div className="text-center py-8 sm:py-12 max-w-[600px] mx-auto">
        <h1 className="font-display text-3xl sm:text-4xl font-bold mb-3">
          LC Accounting <em className="text-primary not-italic">2026</em>
        </h1>
        <p className="text-sm text-muted-foreground font-light leading-relaxed">
          Higher Level revision tools, theory practice, and exam preparation. Study priorities are generated by statistical analysis of 25 years of past papers.
        </p>
      </div>

      {/* Progress Dashboard */}
      <Card className="mb-8 border-border">
        <CardContent className="p-4 sm:p-5">
          <div className="flex flex-wrap gap-5 justify-center">
            {[
              { label: "Questions", value: stats.questions },
              { label: "Score", value: stats.practice },
              { label: "Flashcards", value: stats.flashcards },
              { label: "Classify", value: stats.classify },
              { label: "Practice", value: stats.tracker },
            ].map(item => (
              <div key={item.label} className="text-center min-w-[70px]">
                <div className="font-mono text-xl font-bold text-primary">{item.value}</div>
                <div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground mt-0.5">{item.label}</div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Tool Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-10">
        {TOOLS.map(tool => (
          <Link key={tool.href} to={tool.href} className="group block">
            <Card className={`h-full border-t-4 transition-all hover:shadow-md hover:-translate-y-0.5 ${tool.color}`}>
              <CardContent className="p-5">
                <h3 className="font-display text-base font-bold mb-1.5">{tool.name}</h3>
                <p className="text-xs text-muted-foreground font-light leading-relaxed mb-2.5">{tool.desc}</p>
                <span className="font-mono text-[11px] font-bold text-primary">{tool.stat}</span>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>

      {/* Q5 Guaranteed Banner */}
      <div className="flex items-center gap-4 bg-sage-bg border border-border rounded-xl p-4 sm:p-5 mb-6">
        <Badge className="bg-tier-vl text-white text-[10px] font-bold shrink-0">EVERY YEAR</Badge>
        <p className="text-sm font-medium">
          Q5 Interpretation of Accounts is guaranteed. Memorise the 20 ratio formulas.{" "}
          <Link to="/ratios" className="text-primary font-bold underline underline-offset-2">Q5 Ratios Hub</Link>
        </p>
      </div>

      {/* Section 2 Priorities */}
      <SectionHeader title="Section 2 — Where to Focus for Q6 / Q7" sub="Based on historical patterns, Markov chain analysis, and recurrence intervals." />
      <div className="space-y-3 mb-8">
        {shown.map((r, i) => {
          const t = tier(r.prob);
          const reason = r.yearsSinceLast && r.yearsSinceLast >= 2 && r.markovProb > 50
            ? `Absent for ${r.yearsSinceLast} years. Markov probability is ${r.markovProb}%. MRI is ${r.mri} years.`
            : r.note;
          return (
            <Card key={r.key} className="border-l-4 hover:shadow-sm transition-shadow" style={{ borderLeftColor: t.color }}>
              <CardContent className="p-4 flex items-start gap-4">
                <span className="font-mono text-xl font-bold shrink-0 w-8 text-center" style={{ color: t.color }}>
                  {i + 1}
                </span>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-sm font-bold">{r.key}</span>
                    <Badge variant="outline" className="text-[9px] px-2 py-0" style={{ color: t.color, borderColor: t.color + "44", background: t.color + "11" }}>
                      {t.label}
                    </Badge>
                  </div>
                  <p className="text-xs text-muted-foreground font-light leading-relaxed">{reason}</p>
                  <p className="text-[11px] font-mono text-muted-foreground mt-1.5">
                    {r.appearances.length} appearances · Last: {r.lastYear} · Avg gap: {r.gap} yrs
                  </p>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Section 3 */}
      <SectionHeader title="Section 3 — Q8 (Costing) and Q9 (Budgeting)" sub="Q8 is always Costing. Q9 is always Budgeting. Students pick one from each." />
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
        <div>
          <p className="text-sm font-bold mb-2.5">Q8 — Costing</p>
          {q8top.map(r => {
            const t = tier(r.prob);
            return (
              <Card key={r.key} className="mb-2 border-l-[3px]" style={{ borderLeftColor: t.color }}>
                <CardContent className="p-3">
                  <p className="text-xs font-bold">{r.key}</p>
                  <p className="text-[10px] text-muted-foreground mt-0.5">Last: {r.lastYear || "N/A"}</p>
                </CardContent>
              </Card>
            );
          })}
        </div>
        <div>
          <p className="text-sm font-bold mb-2.5">Q9 — Budgeting</p>
          {q9top.map(r => {
            const t = tier(r.prob);
            return (
              <Card key={r.key} className="mb-2 border-l-[3px]" style={{ borderLeftColor: t.color }}>
                <CardContent className="p-3">
                  <p className="text-xs font-bold">{r.key}</p>
                  <p className="text-[10px] text-muted-foreground mt-0.5">Last: {r.lastYear || "N/A"}</p>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>

      {/* Q1 Pairs */}
      <SectionHeader title="Section 1 — Q1 Account Type Pairs" sub="Two account types appear each year. The pair-based model analyses which combination is most likely." />
      <div className="space-y-3 mb-10">
        {Q1_PAIRS.map((p, i) => {
          const colors = ["hsl(var(--tier-vl))", "hsl(var(--tier-po))", "hsl(var(--tier-un))"];
          return (
            <Card key={p.pair} className="border-l-4" style={{ borderLeftColor: colors[i] }}>
              <CardContent className="p-4 flex items-start gap-4">
                <span className="font-mono text-lg font-bold shrink-0" style={{ color: colors[i] }}>{p.prob}%</span>
                <div>
                  <p className="text-sm font-bold mb-1">{p.pair}</p>
                  <p className="text-xs text-muted-foreground font-light">{p.reason}</p>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Patch Notes */}
      <SectionHeader title="Patch Notes" sub="Recent updates and improvements to the study guide." />
      <div className="space-y-3 mb-8">
        {[
          { version: "v2.6", date: "13 Apr 2026", items: ["Past Papers page added — SEC papers (2005–2025) linked from examinations.ie, 7 mock papers + marking schemes hosted locally", "Theory chapter cards compacted into 2-column grid to reduce scrolling on iPad", "Keyboard navigation (← →) added to chapter reading view"] },
          { version: "v2.5", date: "10 Apr 2026", items: ["Chapter Review quiz system added at end of each theory chapter", "iPad/tablet layout optimisation across all pages", "Walkthrough notes now display in 2-column grid on tablet"] },
          { version: "v2.4", date: "5 Apr 2026", items: ["Rebuilt Learn Mode with original 5-module layout, interactive quizzes, fill-in practice", "Added sequential T-account reveal to all Workings pages", "Theory Practice Mode revamped with self-scoring quiz flow"] },
          { version: "v2.3", date: "28 Mar 2026", items: ["Q8 Costing & Q9 Budgeting full question walkthroughs added", "Section 2 Workings expanded to 37 archetypes", "Prediction engine updated with 2025 paper data"] },
          { version: "v2.2", date: "15 Mar 2026", items: ["Q1 Adjustment Guide with filterable categories", "Classify game for BS/P&L item classification", "Formula cheat sheet with all key formulas"] },
          { version: "v2.1", date: "1 Mar 2026", items: ["Dark mode support", "Q5 Ratios Hub with practice papers and formula quiz", "Study planner and exam timing calculator"] },
        ].map(patch => (
          <Card key={patch.version} className="border-border">
            <CardContent className="p-4">
              <div className="flex items-center gap-2 mb-2">
                <span className="font-mono text-xs font-bold text-primary bg-primary/10 px-2 py-0.5 rounded">{patch.version}</span>
                <span className="text-[10px] text-muted-foreground font-mono">{patch.date}</span>
              </div>
              <ul className="space-y-1">
                {patch.items.map((item, j) => (
                  <li key={j} className="text-xs text-muted-foreground font-light leading-relaxed flex items-start gap-1.5">
                    <span className="text-primary mt-0.5 shrink-0">•</span>
                    {item}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Updates Paused Notice */}
      <Card className="mb-8 border-border bg-muted/30">
        <CardContent className="p-4 text-center">
          <p className="text-sm font-medium text-foreground mb-1">Updates paused until after the Leaving Cert</p>
          <p className="text-xs text-muted-foreground font-light">The developer is focusing on their own LC exams. New features will resume after June 2026. Good luck to everyone sitting the exam!</p>
        </CardContent>
      </Card>

      {/* Coming Soon */}
      <SectionHeader title="Coming Soon" sub="Features planned for after the Leaving Cert." />
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-10">
        {[
          { title: "Timed Mock Exams", desc: "Full exam simulations with real past papers, auto-timing, and score tracking.", status: "Planned" },
          { title: "Marking Scheme Viewer", desc: "Side-by-side view of questions and official SEC marking schemes with annotations.", status: "Planned" },
          { title: "Mobile App (PWA)", desc: "Install as an app on your phone for offline access to all study materials.", status: "Planned" },
        ].map(item => (
          <Card key={item.title} className="border-border border-dashed">
            <CardContent className="p-4">
              <div className="flex items-center gap-2 mb-1.5">
                <h3 className="text-sm font-bold">{item.title}</h3>
                <Badge variant="outline" className="text-muted-foreground border-border text-[9px] px-2 py-0">
                  {item.status}
                </Badge>
              </div>
              <p className="text-xs text-muted-foreground font-light leading-relaxed">{item.desc}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Quick Links */}
      <div className="flex flex-wrap gap-2 mb-6">
        {[
          { to: "/learn", label: "Learn Mode (5 Modules)" },
          { to: "/theory", label: "Theory + Flashcards" },
          { to: "/study-tools", label: "Study Planner" },
          { to: "/q1-guide", label: "Q1 Adjustment Reference" },
          { to: "/q1-workings", label: "Q1 Workings (37)" },
          { to: "/s2-workings", label: "S2 Workings (37)" },
          { to: "/ratios", label: "Q5 Ratios Hub" },
          { to: "/q8-costing", label: "Q8 Costing (27)" },
          { to: "/q9-budgeting", label: "Q9 Budgeting (24)" },
          { to: "/layouts", label: `Layout Practice (${LAYOUT_FORMATS.length})` },
          { to: "/classify", label: `Classify (${CLASSIFY_ITEMS.length} Items)` },
          { to: "/formulas", label: "Formula Cheat Sheet" },
          { to: "/contact", label: "Contact & Feedback" },
        ].map(link => (
          <Link
            key={link.to}
            to={link.to}
            className="bg-card border border-border rounded-lg px-3 py-1.5 text-xs font-semibold text-muted-foreground hover:border-primary hover:text-primary transition-colors"
          >
            {link.label}
          </Link>
        ))}
      </div>

      <p className="text-center text-xs text-muted-foreground font-light leading-relaxed">
        Study priorities are generated by a statistical forecasting model analysing verified HL exam data from 2001 to 2025.
      </p>
    </div>
  );
}

function SectionHeader({ title, sub }: { title: string; sub: string }) {
  return (
    <>
      <h2 className="font-display text-lg font-bold mt-8 mb-1 pb-2 border-b border-border">{title}</h2>
      <p className="text-xs text-muted-foreground font-light mb-4">{sub}</p>
    </>
  );
}
